stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/raw
    - src/features/feature_engineering.py
    params:
    - feature_engineering.test_size
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:         
      - random_forest.max_features
      - random_forest.min_samples_leaf
      - random_forest.max_depth
      - random_forest.min_samples_split
      - random_forest.n_estimators
      - random_forest.random_state
    outs:
    - models/rf_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/rf_model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json